// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzcm7tTb9cJ51Z2FgffnWSp3yPG5cSSvE',
    appId: '1:1079641633070:web:38ea15f23225b85eb6cabf',
    messagingSenderId: '1079641633070',
    projectId: 'our-norimaki',
    authDomain: 'our-norimaki.firebaseapp.com',
    storageBucket: 'our-norimaki.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUY-EOU9T8KIjJPuzKt-TyiJQdWQb5I_o',
    appId: '1:1079641633070:android:7ed908a64b184765b6cabf',
    messagingSenderId: '1079641633070',
    projectId: 'our-norimaki',
    storageBucket: 'our-norimaki.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0qbM5f5nB90ODih8jTgBnTkAvMXoM3tg',
    appId: '1:1079641633070:ios:4e9710134a2c488eb6cabf',
    messagingSenderId: '1079641633070',
    projectId: 'our-norimaki',
    storageBucket: 'our-norimaki.appspot.com',
    iosBundleId: 'com.addong.ourNorimaki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0qbM5f5nB90ODih8jTgBnTkAvMXoM3tg',
    appId: '1:1079641633070:ios:3cb4e86b6002fe47b6cabf',
    messagingSenderId: '1079641633070',
    projectId: 'our-norimaki',
    storageBucket: 'our-norimaki.appspot.com',
    iosBundleId: 'com.addong.ourNorimaki.RunnerTests',
  );
}
